# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric / Minecraft
# see https://fabricmc.net/develop for the latest versions
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.14

# Mod properties
mod_version=0.1.0
maven_group=com.moderncraft
archives_base_name=moderncraft

# Dependencies (Fabric API for 1.21.1)
fabric_version=0.107.0+1.21.1
